export PYTHONPATH=../src
test_bind: test_bind.py
	python test_bind.py

test_bspline: test_bspline.py
	pep8 test_bspline.py
	pep8 ../src/bspline.py
	python test_bspline.py

test_hmole: test_hmole.py
	pep8 test_hmole.py
	pep8 ../src/hmole.py
	python test_hmole.py

test_utils: test_utils.py
	pep8 test_utils.py
	pep8 ../src/utils.py
	python test_utils.py
